name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Automated_Tests:
    name: Test
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: pfdb
        ports:
          - 5434:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16.5
        cache: true
        # cache-dependency-path: subdir/go.sum
      id: go
    - name: Check Go code formatting
      run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            gofmt -s -l .
            echo "Please format Go code by running: go fmt ./..."
            exit 1
          fi
    - name: Check Go Vet
      run : go vet ./...
#     - name: Install Additional dependencies
#       run : |
#           go install github.com/pressly/goose/v3/cmd/goose@latest

    # Migrations Steps
#     - name: Install goose package
#       run: go install github.com/pressly/goose/v3/cmd/goose@latest
    - name: Run Migrations
      run: make migrateup
      
    # Run Tests
    - name: Storage Test
      run: make test
